version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8089:8089"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./database.db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
